package pizza;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import static javax.swing.JOptionPane.showMessageDialog;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author david
 */
public class ControleFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form Funcionario
     */
    public ControleFuncionario() {
        initComponents();
        

        
        try
        {
          String myDriver = "org.gjt.mm.mysql.Driver";
          String myUrl = "jdbc:mysql://localhost/pizzaria";
          Class.forName(myDriver);
          Connection conn = DriverManager.getConnection(myUrl, "root", "");
          
          String query = "SELECT idfunc FROM loginfuncionario";
          
          Statement st = conn.createStatement();
          
          ResultSet rs = st.executeQuery(query);
          
          cmb_ID.removeAllItems();
          while(rs.next()){
              cmb_ID.addItem(rs.getInt("idfunc")+"");
          }
                  st.close();

        }
        catch (Exception e)
        {
          System.err.println("Erro! ");
          System.err.println(e.getMessage());
        }
        if(Login.tipoFunc == 1){
            
        }else{
            txt_Tipo.setEditable(false);
            cmb_ID.setSelectedItem(Login.idfunc+"");
            cmb_ID.setEnabled(false);
            btn_Criar.setEnabled(false);
            btn_Deletar.setEnabled(false);
            System.out.print("O ID do func: "+Login.idfunc);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Criar = new javax.swing.JButton();
        btn_Novo = new javax.swing.JButton();
        txt_Nome = new javax.swing.JTextField();
        btn_Alterar = new javax.swing.JButton();
        txt_Tipo = new javax.swing.JTextField();
        btn_Deletar = new javax.swing.JButton();
        txt_Tel = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        txt_Endereco = new javax.swing.JTextField();
        txt_CPF = new javax.swing.JTextField();
        lbl_Titulo = new java.awt.Label();
        lbl_Nome = new javax.swing.JLabel();
        lbl_Tipo = new javax.swing.JLabel();
        lbl_Tel = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        lbl_Endereco = new javax.swing.JLabel();
        lbl_CPF = new javax.swing.JLabel();
        lbl_ID = new javax.swing.JLabel();
        cmb_ID = new javax.swing.JComboBox<>();
        lbl_Senha = new javax.swing.JLabel();
        txt_Senha = new javax.swing.JPasswordField();
        btn_Voltar = new javax.swing.JButton();
        txt_Placa = new javax.swing.JTextField();
        lbl_CPF1 = new javax.swing.JLabel();
        txt_Veiculo = new javax.swing.JTextField();
        lbl_CPF2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btn_Criar.setText("CRIAR");
        btn_Criar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CriarActionPerformed(evt);
            }
        });

        btn_Novo.setText("NOVO");
        btn_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NovoActionPerformed(evt);
            }
        });

        btn_Alterar.setText("ALTERAR");
        btn_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AlterarActionPerformed(evt);
            }
        });

        btn_Deletar.setText("DELETAR");
        btn_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeletarActionPerformed(evt);
            }
        });

        lbl_Titulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_Titulo.setText("FUNCIONÁRIOS");

        lbl_Nome.setText("Nome:");

        lbl_Tipo.setText("Tipo:");

        lbl_Tel.setText("Telefone:");

        lbl_Email.setText("Email:");

        lbl_Endereco.setText("Endereço:");

        lbl_CPF.setText("CPF:");

        lbl_ID.setText("ID:");

        cmb_ID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_IDItemStateChanged(evt);
            }
        });
        cmb_ID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_IDMouseClicked(evt);
            }
        });
        cmb_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_IDActionPerformed(evt);
            }
        });

        lbl_Senha.setText("Senha:");

        btn_Voltar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_Voltar.setText("<- Voltar");
        btn_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoltarActionPerformed(evt);
            }
        });

        lbl_CPF1.setText("Placa:");

        lbl_CPF2.setText("Veiculo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl_CPF2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Criar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Alterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Deletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_Nome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_Nome))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_Senha)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_Senha))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbl_Email)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_Email))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_Tel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_Tel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_Endereco)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_Endereco))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_Tipo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_Tipo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbl_CPF)
                                            .addComponent(lbl_CPF1))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_CPF))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(txt_Placa)
                                                .addGap(101, 101, 101))))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Voltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(lbl_ID)))
                        .addGap(18, 18, 18)
                        .addComponent(cmb_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_ID)
                        .addComponent(cmb_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_Voltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Nome)
                    .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Senha)
                    .addComponent(txt_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Tipo)
                    .addComponent(txt_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Tel)
                    .addComponent(txt_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Email)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Endereco)
                    .addComponent(txt_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_CPF)
                    .addComponent(txt_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Criar)
                    .addComponent(btn_Alterar)
                    .addComponent(txt_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_CPF1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Novo)
                            .addComponent(btn_Deletar)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_CPF2))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CriarActionPerformed
       Funcionario f = new Funcionario();
       String Senha = new String((txt_Senha.getPassword()));
       String Nome = txt_Nome.getText();
       int Tipo = Integer.parseInt(txt_Tipo.getText());
       String Endereco = txt_Endereco.getText();
       String Telefone = txt_Tel.getText();
       String CPF = txt_CPF.getText();
       String Email = txt_Email.getText();
       String Placa = txt_Placa.getText();
       String Veiculo = txt_Veiculo.getText();
       
       f.setSenha(Senha);
       f.setNome(Nome);
       f.setTipo(Tipo);
       f.setEndereco(Endereco);
       f.setTelefone(Telefone);
       f.setCpf(CPF);
       f.setEmail(Email);
       f.setPlaca(Placa);
       f.setVeiculo(Veiculo);
       

       int res = f.CriarFunc();
       
       if(Tipo == 3){   
        try
        {
          String myDriver = "org.gjt.mm.mysql.Driver";
          String myUrl = "jdbc:mysql://localhost/pizzaria";
          Class.forName(myDriver);
          Connection conn = DriverManager.getConnection(myUrl, "root", "");
          
          String queryt = "SELECT MAX(idfunc) as Max FROM loginfuncionario";
          
          Statement stT = conn.createStatement();
          
          ResultSet rsT = stT.executeQuery(queryt);
          
          rsT.next();
          int IDfunc_t3 = Integer.parseInt(rsT.getInt("Max")+"");
        
          f.setIdfunc(IDfunc_t3);
          
          res = f.AdicionarAposFunc();
          stT.close();
        } 
        catch (Exception e)
        {
          System.err.println("Erro no TIPO 3! ");
          System.err.println(e.getMessage());
        }
       
       if(res == 1){
           showMessageDialog(null, "Inserido com sucesso!");
       }
       }
    }//GEN-LAST:event_btn_CriarActionPerformed

    private void btn_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AlterarActionPerformed
        // TODO add your handling code here:
       if(Login.tipoFunc != 1){
        Funcionario f = new Funcionario();
        int ID = Integer.parseInt(cmb_ID.getSelectedItem().toString());
        String Senha = new String((txt_Senha.getPassword()));
        String Nome = txt_Nome.getText();
        int Tipo = Integer.parseInt(txt_Tipo.getText());
        String Endereco = txt_Endereco.getText();
        String Telefone = txt_Tel.getText();
        String CPF = txt_CPF.getText();
        String Email = txt_Email.getText();
        String Placa = txt_Placa.getText();
        String Veiculo = txt_Veiculo.getText();

        f.setIdfunc(ID);
        f.setSenha(Senha);
        f.setNome(Nome);
        f.setTipo(Tipo);
        f.setEndereco(Endereco);
        f.setTelefone(Telefone);
        f.setCpf(CPF);
        f.setEmail(Email);
        f.setPlaca(Placa);
        f.setVeiculo(Veiculo);

        int res = f.AlterarFunc();
        
        
            if(Tipo == 3){
                res = f.AlterarAposFunc();
            }

        if(res == 1){
            showMessageDialog(null, "Alterado com sucesso!");
        }
       } else{
        Gerente f = new Gerente();
        int ID = Integer.parseInt(cmb_ID.getSelectedItem().toString());
        String Senha = new String((txt_Senha.getPassword()));
        String Nome = txt_Nome.getText();
        int Tipo = Integer.parseInt(txt_Tipo.getText());
        String Endereco = txt_Endereco.getText();
        String Telefone = txt_Tel.getText();
        String CPF = txt_CPF.getText();
        String Email = txt_Email.getText();
        String Placa = txt_Placa.getText();
        String Veiculo = txt_Veiculo.getText();

        f.setIdfunc(ID);
        f.setSenha(Senha);
        f.setNome(Nome);
        f.setTipo(Tipo);
        f.setEndereco(Endereco);
        f.setTelefone(Telefone);
        f.setCpf(CPF);
        f.setEmail(Email);
        f.setPlaca(Placa);
        f.setVeiculo(Veiculo);

        int res = f.AlterarFunc();
        
        if(Tipo == 3){
                res = f.AlterarAposFunc();
            }
        

        if(res == 1){
            showMessageDialog(null, "Alterado com sucesso!");
        }  
       }
    }//GEN-LAST:event_btn_AlterarActionPerformed

    private void cmb_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_IDActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_cmb_IDActionPerformed

    private void btn_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeletarActionPerformed
        // TODO add your handling code here:
       Funcionario f = new Funcionario();
       int ID = Integer.parseInt(cmb_ID.getSelectedItem().toString());
       f.setIdfunc(ID);
       
       int res = f.ExcluirFunc();
        if(res == 1){
           showMessageDialog(null, "Excluido com sucesso!");
       }
    }//GEN-LAST:event_btn_DeletarActionPerformed

    private void cmb_IDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_IDMouseClicked
        // TODO add your handling code here:
        if(Login.tipoFunc == 1){
        cmb_ID.removeAllItems();
        try
        {
          String myDriver = "org.gjt.mm.mysql.Driver";
          String myUrl = "jdbc:mysql://localhost/pizzaria";
          Class.forName(myDriver);
          Connection conn = DriverManager.getConnection(myUrl, "root", "");
          
          String query = "SELECT * FROM loginfuncionario";
          
          Statement st = conn.createStatement();
          
          ResultSet rs = st.executeQuery(query);
          
          while(rs.next()){
              rs.getInt("idfunc");
              cmb_ID.addItem(rs.getInt("idfunc")+"");
              
          }
          st.close();
          
        }
        catch (Exception e)
        {
          System.err.println("Erro no mouse click! ");
          System.err.println(e.getMessage());
        } 
        }
    }//GEN-LAST:event_cmb_IDMouseClicked

    private void cmb_IDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_IDItemStateChanged
        // TODO add your handling code here:
        try
        {
          String myDriver = "org.gjt.mm.mysql.Driver";
          String myUrl = "jdbc:mysql://localhost/pizzaria";
          Class.forName(myDriver);
          Connection conn = DriverManager.getConnection(myUrl, "root", "");
          
          String query = "SELECT * FROM loginfuncionario WHERE idfunc ="+cmb_ID.getSelectedItem()+"";
          
          String query1 = "SELECT * FROM entregador_func WHERE id_entregador ="+cmb_ID.getSelectedItem()+"";
          
          Statement st = conn.createStatement();
          
          ResultSet rs = st.executeQuery(query);
          
          Statement st1 = conn.createStatement();
          
          ResultSet rs1 = st1.executeQuery(query1);
          
          rs.next();
          rs1.next();
          
          txt_Nome.setText(rs.getString("nome"));
          txt_Endereco.setText(rs.getString("endereco"));
          txt_Tel.setText(rs.getString("telefone"));
          txt_Email.setText(rs.getString("email"));
          txt_Tipo.setText(rs.getInt("tipo")+"");
          txt_CPF.setText(rs.getString("cpf"));
          txt_Placa.setText(rs1.getString("placa"));
          txt_Veiculo.setText(rs1.getString("veiculo"));
          
          st.close();
          st1.close();
          
        }
        catch (Exception e)
        {
          System.err.println("Erro no itemchanged! ");
          System.err.println(e.getMessage());
        }
        
    }//GEN-LAST:event_cmb_IDItemStateChanged

    private void btn_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NovoActionPerformed
        // TODO add your handling code here:
          txt_Nome.setText("");
          txt_Senha.setText("");
          txt_Endereco.setText("");
          txt_Tel.setText("");
          txt_Email.setText("");
          txt_Tipo.setText("");
          txt_CPF.setText("");
          txt_Placa.setText("");
          txt_Veiculo.setText("");
    }//GEN-LAST:event_btn_NovoActionPerformed

    private void btn_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarActionPerformed
        // TODO add your handling code here:
        if(Login.tipoFunc == 1){
            this.setVisible(false);
            new MenuGerente().setVisible(true);
            this.dispose();
        }
        else if (Login.tipoFunc == 2){
            this.setVisible(false);
            new MenuAtendente().setVisible(true);
            this.dispose();
        }else{
            this.setVisible(false);
            new MenuEntregador().setVisible(true);
            this.dispose(); 
        }
    }//GEN-LAST:event_btn_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControleFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControleFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControleFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControleFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControleFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Alterar;
    private javax.swing.JButton btn_Criar;
    private javax.swing.JButton btn_Deletar;
    private javax.swing.JButton btn_Novo;
    private javax.swing.JButton btn_Voltar;
    private javax.swing.JComboBox<String> cmb_ID;
    private javax.swing.JLabel lbl_CPF;
    private javax.swing.JLabel lbl_CPF1;
    private javax.swing.JLabel lbl_CPF2;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_Endereco;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JLabel lbl_Nome;
    private javax.swing.JLabel lbl_Senha;
    private javax.swing.JLabel lbl_Tel;
    private javax.swing.JLabel lbl_Tipo;
    private java.awt.Label lbl_Titulo;
    private javax.swing.JTextField txt_CPF;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_Endereco;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_Placa;
    private javax.swing.JPasswordField txt_Senha;
    private javax.swing.JTextField txt_Tel;
    private javax.swing.JTextField txt_Tipo;
    private javax.swing.JTextField txt_Veiculo;
    // End of variables declaration//GEN-END:variables
}
